-- M4.3 — Tool & material checklist agent.
--
-- Vision ¶24: "rarely forget a tool or the right materials."
--
-- One pre-departure checklist per appointment. Generated by the LLM
-- from the appointment agenda + the contract scope + the contractor's
-- category, then surfaced as both a contractor-dashboard tile and a
-- notification sent ~2h before the appointment (alongside the M3.5
-- reminder). The contractor checks off items in the dashboard; the
-- checked-state lives in the items jsonb so we don't fan out a row
-- per item.
--
-- v1 generates fresh per appointment (Q4.3a recommendation (a)). v1.1
-- caches by (category, scope_hash). v2 graduates to a curated library.
--
-- Tier gate: bronze+. Free-tier contractors see an upsell instead of
-- the tile; cron skips generation entirely for them.

CREATE TABLE IF NOT EXISTS public.appointment_checklists (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  appointment_id  uuid NOT NULL UNIQUE REFERENCES public.appointments(id) ON DELETE CASCADE,
  contractor_id   uuid NOT NULL REFERENCES public.contractors(id) ON DELETE CASCADE,
  -- The structured payload. Shape:
  --   [{ id: text, kind: 'tool'|'material'|'confirmation',
  --      text: string, checked_at?: timestamptz, checked_by_user_id?: uuid }]
  -- Order matters — array index is display order.
  items           jsonb NOT NULL DEFAULT '[]'::jsonb,
  model           text,         -- which LLM produced the v1 generation
  generated_at    timestamptz NOT NULL DEFAULT now(),
  -- Audit context (prompt hash, regeneration reason, etc.)
  context         jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_appointment_checklists_contractor
  ON public.appointment_checklists (contractor_id);

DROP TRIGGER IF EXISTS appointment_checklists_touch_updated_at
  ON public.appointment_checklists;
CREATE TRIGGER appointment_checklists_touch_updated_at
  BEFORE UPDATE ON public.appointment_checklists
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

ALTER TABLE public.appointment_checklists ENABLE ROW LEVEL SECURITY;

-- The claimed contractor can read their own checklist rows. Service
-- role (cron, generator) bypasses RLS.
DROP POLICY IF EXISTS "appointment_checklists: claimer-read"
  ON public.appointment_checklists;
CREATE POLICY "appointment_checklists: claimer-read"
  ON public.appointment_checklists
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.contractors c
      WHERE c.id = appointment_checklists.contractor_id
        AND c.claimed_by_user_id = auth.uid()
    )
  );

-- Checklist mutations (check-off) go through service-role API routes
-- so we don't need an UPDATE policy here. The route verifies the
-- caller is the claimed contractor before patching the row.

-- Tracking column on appointments so the cron can mark "checklist
-- notification already dispatched" without re-reading items. Mirrors
-- the reminder_24h_sent_at / reminder_2h_sent_at pattern.
ALTER TABLE public.appointments
  ADD COLUMN IF NOT EXISTS checklist_notified_at timestamptz;
